# Generated by Django 5.2.7 on 2025-11-04 21:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cle', models.CharField(max_length=50, unique=True)),
                ('valeur', models.TextField()),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuration de session',
                'verbose_name_plural': 'Configurations de session',
            },
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid_carte', models.CharField(max_length=32, unique=True, verbose_name='UID de la carte')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('date_naissance', models.DateField(verbose_name='Date de naissance')),
                ('lieu_naissance', models.CharField(max_length=100, verbose_name='Lieu de naissance')),
                ('departement_naissance', models.CharField(max_length=100, verbose_name='Département de naissance')),
                ('pays_naissance', models.CharField(max_length=100, verbose_name='Pays de naissance')),
                ('nationalite', models.CharField(max_length=100, verbose_name='Nationalité')),
                ('entreprise', models.CharField(max_length=100, verbose_name='Entreprise')),
                ('present', models.BooleanField(default=False, verbose_name='Présent')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='HistoriquePresence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_action', models.CharField(choices=[('ENTREE', 'Entrée'), ('SORTIE', 'Sortie')], max_length=10, verbose_name="Type d'action")),
                ('horodatage', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date et heure')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='presence.utilisateur', verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Historique de présence',
                'verbose_name_plural': 'Historiques de présence',
                'ordering': ['-horodatage'],
            },
        ),
    ]
