# Generated by Django 5.1.13 on 2025-11-04 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presence', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='blackliste',
            field=models.BooleanField(default=False, verbose_name='Blacklisté'),
        ),
    ]
