# Generated by Django 5.2.7 on 2025-11-13
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('presence', '0002_utilisateur_blackliste'),
    ]

    operations = [
        migrations.CreateModel(
            name='BadgeVisiteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid_carte', models.CharField(max_length=32, unique=True, verbose_name='UID du badge visiteur')),
                ('date_attribution', models.DateTimeField(blank=True, null=True, verbose_name="Date d'attribution")),
                ('commentaire', models.CharField(blank=True, default='', max_length=200, verbose_name='Commentaire')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('affecte_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='badges_visiteurs', to='presence.utilisateur', verbose_name='Affecté à')),
            ],
            options={
                'verbose_name': 'Badge visiteur',
                'verbose_name_plural': 'Badges visiteurs',
                'ordering': ['uid_carte'],
            },
        ),
    ]
