# Generated by Django 5.2.7 on 2025-11-13
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presence', '0003_badgevisiteur'),
    ]

    operations = [
        migrations.AddField(
            model_name='badgevisiteur',
            name='nom',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Nom du badge'),
        ),
    ]
