# Generated by Django 5.2.7 on 2026-01-15 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presence', '0005_utilisateur_statut_validation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='departement_naissance',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='entreprise',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='pays_naissance',
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='departement_pays',
            field=models.CharField(default='', max_length=150, verbose_name='Département/Pays'),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='societe_raison',
            field=models.CharField(default='', max_length=200, verbose_name='Société/Raison de la visite'),
        ),
    ]
